### ISSUE TITLE
[BUG] - cloud-controller-manager example - region is mentioned but missing

### ISSUE THREAD

**Issue by eran101** [vultr/vultr-cloud-controller-manager#134]
**Describe the bug**

In cloud-controller-manager example the [region value is mentioned in line 7](https://github.com/vultr/vultr-cloud-controller-manager/blob/c191e2638d484c8a3fb3edca0656cb53d6696853/docs/examples/cloud-controller-manager.yml#L7):
"# Replace the api-key and region with proper values"
However, there's no setting to configure the value.

**To Reproduce**
1. Go to [cloud-controller-manager.yml , line 7](https://github.com/vultr/vultr-cloud-controller-manager/blob/c191e2638d484c8a3fb3edca0656cb53d6696853/docs/examples/cloud-controller-manager.yml#L7) 
2. There is no line in the file where region variable exist as opposed to the API key.

**Expected behavior**
Region value should exist in the file and should be replaced like the [API key value](https://github.com/vultr/vultr-cloud-controller-manager/blob/master/docs/examples/cloud-controller-manager.yml#L8).

**Screenshots**
Not required.

**Desktop (please complete the following information where applicable:**
Not required.

**Additional context**

None

**Comment by happytreees** [comment]
Fixed in #210
