### ISSUE TITLE
CSI and block storage

### ISSUE THREAD

**Issue by vitobotta** [vultr/vultr-cloud-controller-manager#20]
Hi! Is a CSI driver, either in the controller manager or separate, planned? Thanks!

**Comment by ddymko** [comment]
The CSI is not in the controller manager. It is currently in development and we are planning to release that soon.

**Comment by vitobotta** [comment]
Thanks

**Comment by ddymko** [comment]
Hey @vitobotta 

We just open sourced the CSi - https://github.com/vultr/vultr-csi

**Comment by vitobotta** [comment]
@ddymko Sounds great, thanks!
