### ISSUE TITLE
[Question] - Is there anyway to automatically scale a Kubernetes Cluster so it reflects in Vultr billing?

### ISSUE THREAD

**Issue by mangoplane** [vultr/vultr-cloud-controller-manager#227]
Hi,

I had a question regarding Vultr in relation to on-demand pricing. How might one automatically adjust Vultr resource allocation to reflect actual demand, possibly making use of Kubernetes autoscaling to do so?

It seems like the node pool size is fixed, so the Kubernetes autoscaling won't affect the actual underlying resource allocation and the associated Vultr billing cost. I was hoping to simulate something a bit like AWS Lambda functions, where idle time is basically free.

Cheers!

**Comment by optik-aper** [comment]
@mangoplane Thanks for the question.  This isn't really relevant to this repo, so I'm going to close it.  But you can review the [autoscaler documentation](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/vultr/README.md) or use the [API](https://www.vultr.com/api/#tag/kubernetes/operation/update-nodepool) to scale your clusters as needed.  You won't be able to scale a cluster to fewer than 1 nodes, however.
