### ISSUE TITLE
[BUG] - loadBalancerIP not assigning reserver IP

### ISSUE THREAD

**Issue by maxkokocom** [vultr/vultr-cloud-controller-manager#229]
**Describe the bug**
When creating a service of LoadBalancer type I would expect there would either be annotation I can pass or loadBalancerIP field to use previously reserved IP address.

**To Reproduce**
Create a service with field loadBalancerIP
Newly create IP is being assigned

**Expected behavior**

**Comment by happytreees** [comment]
Hello,

Vultr Load Balancer's currently do not support using reserved IP's for the VLB so it is not supported from the CCM either.
