### ISSUE TITLE
[BUG] - Error syncing load balancer

### ISSUE THREAD

**Issue by shutupflanders** [vultr/vultr-cloud-controller-manager#59]
**Describe the bug**
Apologies if this is not the correct place to log this, but I'm also logging it with ingress-nginx.
Had a load balancer completely fail today for no obvious reason, couldn't access the cluster, so I destroyed it and rebuilt it (it's using the Terraform condor plugin)
When bringing everything back up (same versions as prior to destroying it) I'm now getting the below error when trying to bring up a load balancer through ingress-nginx

```
Error syncing load balancer: failed to ensure load balancer: error getting the provider ID : providerID cannot be an empty string
```
The logs in the Vultr CCM pod are spamming this constantly

```
I0114 16:22:49.318052       1 event.go:291] "Event occurred" object="default/ingress-nginx-controller" kind="Service" apiVersion="v1" type="Normal" reason="EnsuringLoadBalancer" message="Ensuring load balancer"
E0114 16:22:49.466674       1 controller.go:275] error processing service default/ingress-nginx-controller (will retry): failed to ensure load balancer: error getting the provider ID  : providerID cannot be an empty string
```

Has anything changed that could cause this in the last 6 months? (that's how long it's been since I brought up the original cluster)
Or is there any way I can debug to find out what `providerID` is? (I've done lots of searching and cannot see any reference to it in either package)

**To Reproduce**
1. Bring up a kubernetes cluster in terraform using [Condor](https://github.com/vultr/terraform-vultr-condor)
2. Install the Helm chart from ingress-nginx
`helm upgrade --install ingress-nginx ingress-nginx   --repo https://kubernetes.github.io/ingress-nginx   --namespace default --values=values.yml`
3. Watch the services for `ingress-nginx-controller` - it will remain in the "Pending" state
4. See the event log says the given error message
5. Check the Vultr CCM pod, see the above error messages

**Expected behavior**
A load balancer to be provisioned

**Screenshots**
N/A

**Desktop (please complete the following information where applicable:**
N/A

**Additional context**

contents of `values.yml` in the reproduction steps:

```yaml
controller:
  config:
    use-forwarded-headers: "true"
    compute-full-forwarded-for: "true"
    use-proxy-protocol: "true"
  service:
    annotations:
      service.beta.kubernetes.io/vultr-loadbalancer-proxy-protocol: "true"
```

Again, sorry if this is the wrong place to post this, please let me know if there's a better place to ask.

**Comment by ddymko** [comment]
@shutupflanders 

The `ProviderID` is assigned by the CCM which is the worker nodes/instances UUID that Vultr has assigned to it.

Heres an an example of the ProviderID that are assigned to 2 of my worker-nodes 

```sh
☁  ~  k describe node | grep "ProviderID"
ProviderID:                   vultr://eeeb7d61-10e2-434c-adb6-e845567767fa
ProviderID:                   vultr://7fa8731e-649b-4105-9b55-780d9898e1df
```

Guessing on the error you have there are worker nodes that haven't been annotated properly by the CCM. This may be a properly specific to condor since you mentioned that in the repro steps. We'll look into condor to see if that provisioning process isn't working.

The reason I think this may be condor specific instead of the CCM is we have a managed kubernetes offering called "Vultr Kubernetes Engine" which uses the CCM and we haven't encountered any issues like this.

https://www.vultr.com/kubernetes/

**Comment by shutupflanders** [comment]
@ddymko 
Thanks for the speedy response!

That does indeed seem the issue:
![image](https://user-images.githubusercontent.com/3372012/149554845-4f0c7896-9c45-442f-bf4f-aefc3cd59f95.png)

I've moved my client's applications over to another cluster for the time being, but I'm looking forward to see if we can sort this out.

Please let me know if there's any more information you need from me!

**Comment by ddymko** [comment]
@shutupflanders 

We tried replicating this with new condor installs and couldn't replicate the issue. I would suggest making a Vultr support ticket so we can dig into this further.
