### ISSUE TITLE
[Feature] - Use different front end and back end protocol in Forwarding Rules

### ISSUE THREAD

**Issue by quanhua92** [vultr/vultr-cloud-controller-manager#96]
**Is your feature request related to a problem? Please describe.**
The front end and back end protocols are always the same as defined at https://github.com/vultr/vultr-cloud-controller-manager/blob/master/vultr/loadbalancers.go#L603
In the Vultr Load Balancer, it is possible to use HTTPS on the LB Protocol and HTTP on the Instance Protocol.
I want to use SSL termination at the Vultr Load Balancer so my application doesn't have to care about the SSL certificates. It works on a manually created Load Balancer where the configuration is HTTPS on the LB Protocol and HTTP on the Instance Protocol.
Currently, the backend protocol is always HTTPS. Therefore, I have to use an additional NGINX reverse proxy to handle the HTTPS. It is unnecessary in my opinion.
Another solution is to use the NGINX ingress controller. That means I can't take advantage of the SSL Termination at the Load Balancer and my nodes have to perform the SSL termination.

**Describe the solution you'd like**
Works the same as Vultr Load Balancer (HTTPS on LB and HTTP on instance protocol)

**Comment by ddymko** [comment]
@quanhua92 We'll look into this
